# Generated by Django 6.0.7 on 2026-08-10 12:33

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='application',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_snapshot',
            field=models.FileField(blank=True, null=True, upload_to='application_resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), profiles.models.validate_resume_size]),
        ),
        migrations.AddField(
            model_name='application',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32, validators=[profiles.models.validate_whatsapp_number]),
        ),
    ]
