# Generated by Django 6.0.7 on 2026-08-09 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_connections', to=settings.AUTH_USER_MODEL)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user_one', 'user_two'), name='unique_connection_pair'), models.CheckConstraint(condition=models.Q(('user_one__lt', models.F('user_two'))), name='connection_pair_canonical_and_not_self'), models.CheckConstraint(condition=models.Q(('initiated_by', models.F('user_one')), ('initiated_by', models.F('user_two')), _connector='OR'), name='connection_initiator_is_participant')],
            },
        ),
    ]
