# Generated by Django 6.0.7 on 2026-08-08 11:40

import django.core.validators
import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, help_text='Upload your resume in PDF format (max 5\u202fMB).', null=True, upload_to='student_resumes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), profiles.models.validate_resume_size]),
        ),
    ]
