# Generated by Django 6.0.7 on 2026-08-10 12:33

import profiles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_studentprofile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=32, validators=[profiles.models.validate_whatsapp_number]),
        ),
    ]
